language: node_js
node_js:
  - "5.0"
  - "4.1"
addons:
  code_climate:
    repo_token: ad59c2e03af9f78977643cc86d8d3e3c6c913c427f24c6522fb6f1410c6a5aa6
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
sudo: false
